spring.application.name=batch

# Porta padrão do Spring Boot
server.port=8080

# Configuração do banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/teste
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do Spring Batch
spring.batch.jdbc.initialize-schema=always
# false -> cada execução um unico job e roda normalmente
spring.batch.job.enabled=false
